I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 499, in script
    if start_character == "Jase":
  File "game/script.rpy", line 499, in <module>
    if start_character == "Jase":
NameError: name 'start_character' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 499, in script
    if start_character == "Jase":
  File "C:\Users\Carlin\Desktop\Apps\renpy-6.99.4-sdk\renpy\ast.py", line 1593, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Carlin\Desktop\Apps\renpy-6.99.4-sdk\renpy\python.py", line 1482, in py_eval
    return eval(py_compile(source, 'eval'), globals, locals)
  File "game/script.rpy", line 499, in <module>
    if start_character == "Jase":
NameError: name 'start_character' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.4.467
raindrops 0.0
